# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/perceptnetfastai',
                'doc_host': 'https://Jorgvt.github.io',
                'git_url': 'https://github.com/Jorgvt/perceptnetfastai',
                'lib_path': 'perceptnetfastai'},
  'syms': { 'perceptnetfastai.data': { 'perceptnetfastai.data.fix_dist_name': ( '00_Data/data_loading.html#fix_dist_name',
                                                                                'perceptnetfastai/data.py'),
                                       'perceptnetfastai.data.get_ref_name': ( '00_Data/data_loading.html#get_ref_name',
                                                                               'perceptnetfastai/data.py')}}}