# AUTOGENERATED! DO NOT EDIT! File to edit: ../Notebooks/00_Data/00_00_data_loading.ipynb.

# %% auto 0
__all__ = []

# %% ../Notebooks/00_Data/00_00_data_loading.ipynb 3
import re

import pandas as pd
from fastai.data.all import *
from fastai.vision.all import *

# %% ../Notebooks/00_Data/00_00_data_loading.ipynb 8
def fix_dist_name(name):
    file, extension = name.split(".")
    file, extension = file.upper(), extension.lower()
    return ".".join([file, extension])

# %% ../Notebooks/00_Data/00_00_data_loading.ipynb 11
def get_ref_name(dist_name):
    file, extension = re.search(r"(.+)_\d+_\d+\.(.+)", dist_name).groups()
    return ".".join((file, extension)).upper()
